class NewsItem {
  final int id; //id (self-generated by postgreSQL)
  final String title; //title
  final String description; //short description
  final String newsType; // product release, franchise opening, festival greetings, etc
  final List<int> imageData; // Binary image data

  NewsItem({
    required this.id,
    required this.title,
    required this.description,
    required this.newsType,
    required this.imageData,
  });

  // Factory constructor to parse data from a map (e.g., from database results)
  factory NewsItem.fromMap(Map<String, dynamic> map) {
    return NewsItem(
      id: map['id'],
      title: map['title'],
      description: map['description'],
      newsType: map['newsType'],
      imageData: List<int>.from(map['imageData']), // Assuming 'imageData' is retrieved as List<int>
    );
  }
}
